version: '3.4'

services:
  apigateway:
    container_name: apigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - userservice
      - playlistservice
    ports:
      - "5010:80"
  rabbitmq:
    image: masstransit/rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"