version: '3.4'

services:
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile

  userservice:
    image: ${DOCKER_REGISTRY-}userservice
    build:
      context: .
      dockerfile: UserService/Dockerfile

  playlistservice:
    image: ${DOCKER_REGISTRY-}playlistservice
    build:
      context: .
      dockerfile: PlaylistService/Dockerfile

