name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
            
  push_to_registry:
    name: Deploy to AKS
    runs-on: ubuntu-latest
    steps:
      - name: Debug - List Manifests Directory Contents
        run: ls -R manifests
      - name: Debug - Print Working Directory
        run: pwd
      - name: Debug - Print File Path
        run: echo "File path:$(pwd)/manifests/userservice-deployment.yaml"
      - name: Apply Kubernetes manifests
        run: kubectl apply -f manifests/userservice-deployment.yaml
