name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Debug - CD
        run: cd ../
      - name: Debug - List Entire Repository Contents
        run: ls -R
      - name: Debug - Print Working Directory
        run: pwd
      - name: Deploy to AKS
        run: kubectl apply -f manifests/userservice-deployment.yaml
