name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
            
  push_to_registry:
    name: Deploy to AKS
    runs-on: ubuntu-latest
    steps:
      - name: Debug - List Directory Contents
        run: ls -R
      - name: Apply Kubernetes manifests
        run: kubectl apply -f Beatify/manifests/userservice-deployment.yaml
