name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
            
  push_to_registry:
    name: Deploy to AKS
    runs-on: ubuntu-latest
    steps:
    
      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Apply Kubernetes manifests
        run: kubectl apply -f Beatify-cluster/manifests/userservice
